#!/bin/bash


if [ $# -ne 0 ]; then
    while getopts s:o option; do
        case "${option}" in
            s) subject=${OPTARG}
               echo $subject;;
            o) optional=${OPTARG};;
        esac
    done

    subjectpath="$HOME/Documents/NTNU/$subject"
    weekpath="/$subjectpath/week$( date +%W )"
    note="$path/lecture$( date +%y-%m-%d ).md"

    if [ ! -f "$note" ]; then
        if [ ! -d "$path" ]; then
            if [ ! -d "$subjectpatht"] ]; then
                mkdir "$subjectpath"
            fi
            #echo "Directory doesn't exist, constructing path"
            mkdir "$path"
        fi
        touch "$note"
    fi

    #$EDITOR "$note"

else
    echo 'Need to pass arguments -s [--subject]'
fi
