#!/bin/bash


if [ $# -ne 0 ]; then
    while getopts s:o option; do
        case "${option}" in
            s) subject=${OPTARG}
               echo $subject;;
            o) optional=${OPTARG};;
        esac
    done

    subjectpath="$HOME/Documents/NTNU/$subject"
    weekpath="$subjectpath/week$( date +%W )"
    note="$weekpath/lecture$( date +%y-%m-%d )"


    #echo $subjectpath
    #echo $weekpath
    #echo $note

    if [ ! -f "$note" ]; then
        if [ ! -d "$weekpath" ]; then
            if [ ! -d "$subjectpath" ]; then
                mkdir "$subjectpath"
            fi
            #echo "Directory doesn't exist, constructing path"
            mkdir "$weekpath"
        fi
        #touch "$note"
        echo "#$subject notes - $(date "+%y-%m-%d : w%W") > "note"
    fi

    echo "$(date +%H:%M:%S)" >> "$note"
    $EDITOR "$note"

else
    echo 'Need to pass arguments -s [--subject]'
fi
