#!/bin/bash


while getopts s:o option; do
    case "${option}" in
        s) 
            subject=${OPTARG}
            echo $subject;;
        o) 
            optional=${OPTARG};;
        *) 
            echo 'Need to pass arguments -s [--subject]'
            exit;;
    esac
done

subjectpath="$HOME/Documents/NTNU/$subject"
weekpath="$subjectpath/week$( date +%W )"
note="$weekpath/lecture$( date +%y-%m-%d )"


#echo $subjectpath
#echo $weekpath
#echo $note

if [ ! -f "$note" ]; then
    if [ ! -d "$weekpath" ]; then
        if [ ! -d "$subjectpath" ]; then
            mkdir "$subjectpath"
        fi
        #echo "Directory doesn't exist, constructing path"
        mkdir "$weekpath"
    fi
    #touch "$note" 
    printf "#%s - $(date "+%y-%m-%d week%W") \nAuthor: %s\n" "$subject" "$USER" > "$note"
fi

#date +%H:%M:%S >> "$note"
$EDITOR "$note"
