#!/bin/bash
# Change keyboard layout between different layouts


layouts=(us no)

current=$(setxkbmap -query | grep 'layout' | awk '{print $2}')

export i=0
for opt in "${layouts[@]}"; do
    if [[ $opt =~ $current ]]; then
        ((i+=1))
        if [ $i -ge ${#layouts[@]} ]; then
            i=$((0))
        fi
        setxkbmap "${layouts[i]}"
        notify-send "Layout: " "${layouts[i]}"
        exit
    fi
    ((i+=1))
done 
notify-send "Kb switch: fail"
